### ISSUE TITLE
encoding: move Wrap* funcs to a codecutil package

### ISSUE THREAD

**Issue by dolmen** [dolanor/rip#10]
About the [`encoding`](https://pkg.go.dev/github.com/dolanor/rip/encoding) API, the [`WrapCodec`](https://pkg.go.dev/github.com/dolanor/rip/encoding#WrapCodec), [`WrapDecoder`](https://pkg.go.dev/github.com/dolanor/rip/encoding#WrapDecoder) and [`WrapEncoder`](https://pkg.go.dev/github.com/dolanor/rip/encoding#WrapEncoder) are utility funcs which are only useful to implementers of [`Codec`](https://pkg.go.dev/github.com/dolanor/rip/encoding#Codec)s: they are implementation details that are not useful to users of the `encoding` package.

So I propose to move them to their own package `github.com/dolanor/rip/encoding/codecutil`. That will make the API of [`encoding`](https://pkg.go.dev/github.com/dolanor/rip/encoding) package lighter and easier to learn.

**Comment by dolanor** [comment]
Good point.

Thanks for all those detail. They will really improve the public API which is something I care about, but I was to entrenched in my hacking mindset of the time.
