### ISSUE TITLE
Improve base template

### ISSUE THREAD

**Issue by dolanor** [dolanor/rip#16]
The current template is not that good in the sense that each resource gives back a full web page code, with headers, etc.
In HTMX, each resource would just render to a simple HTML view of the resource. That would save a bunch data.

If I access the resource directly, I should respond with the full page directly though.

I guess, in the case I get the `HX-Request: true` header to determine which one to chose: full page or just resource.

**Comment by prologic** [comment]
I like the idea of adding HTMX support!

**Comment by dolanor** [comment]
Fixed with 913f60e
But I need to document it correctly.
