### ISSUE TITLE
Type Middleware as type alias

### ISSUE THREAD

**Issue by dolmen** [dolanor/rip#4]
For maximum flexibility type Middleware should be a type alias as it doesn't export any method.

**Comment by dolanor** [comment]
as in
```go
type Middleware = func(http.HandlerFunc) http.HandlerFunc
```
?

I guess I don't understand the difference in that specific case.

**Comment by dolmen** [comment]
At runtime there will not be a specific type allocated. The availability of that specific named type is useless here as what matters is the func signature.

Check `fmt.Printf("%T\n", Middleware(nil))`.

**Comment by dolanor** [comment]
Ok, got it.
Seems like a good idea. I'll get it done.
